### ISSUE TITLE
Settings of Real-IAD, All-View or Single-View?

### ISSUE THREAD

**Issue by guojiajeremy** [lewandofskee/MambaAD#1]
Dear Authors,

Thank you for your great work.

Concerning the multi-class experiments on Real-IAD, I would like to ask whether you adopt the single-view setting that only uses the top view of each object (realiad_json_sv.json), or all-view setting that takes multiple images for each object (realiad_json.json).

This information is vital for our comparison. Thank you!

Best, Jia

**Comment by lewandofskee** [comment]
Thank you for your interest in our work. We used the all-view(5 views) setting for each object in Real-IAD. I hope this answers your questions.
