### ISSUE TITLE
ValueError: invalid module: timm_resnet34

### ISSUE THREAD

**Issue by wrj-best** [lewandofskee/MambaAD#12]
Hello! Thank you for providing this project!
when I run this project,it show that: ValueError: invalid module: timm_resnet34,
how to salve it???

**Comment by renzhaohui0918** [comment]
Hello, I also have this problem and would like to ask you how it was solved? If you could reply to me, that would be the best.

**Comment by renzhaohui0918** [comment]
Hello, I also have this problem and would like to ask you how it was solved? If you could reply to me, that would be the best.
