### ISSUE TITLE
 File "mambaad_trainer.py", line 10, in <module>     from util.util import makedirs, log_cfg, able, log_msg, get_log_terms, update_log_term ModuleNotFoundError: No module named 'util'

### ISSUE THREAD

**Issue by yaoyaoyao13** [lewandofskee/MambaAD#5]
Hello author, I have installed the package required by the project, but it still shows this problem

**Comment by yaoyaoyao13** [comment]
<img width="351" alt="1714135865717" src="https://github.com/lewandofskee/MambaAD/assets/143946108/5b384689-7d88-4f02-8c78-e332821de5d6">

**Comment by lewandofskee** [comment]
Hi, you should install this repo as well as [ADer](https://github.com/zhangzjn/ADer). And clone this repo to ADer.
