### ISSUE TITLE
About MambaAD-main/model/mambaad.py

### ISSUE THREAD

**Issue by L1lBURY** [lewandofskee/MambaAD#6]
Hi, I am very interested in your work and I would like to know what modules the “model” is in the two lines of code:
“from model import get_model”
“from model import MODEL” 
in Mamba main/model/mambaad.py. 
Looking forward to your reply

**Comment by lewandofskee** [comment]
Thank you for your interest in our work. Our algorithm is based on the [ADer](https://github.com/zhangzjn/ADer) framework, so please put all the files into the ADer framework to run it. The two lines you mentioned are also shown in [ADer/model](https://github.com/zhangzjn/ADer/blob/main/model/__init__.py).

**Comment by L1lBURY** [comment]
Thank you for your reply, it has been very helpful to me!&nbsp;
In addition, when I was reproducing your code, I saw that you used:
“model/pretrain/wide.resnet50_racm-8234f177.pth”
“model/pretrain/resnet34-43635321. pth”
I would greatly appreciate it if you could provide these two pre training model files!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lewandofskee/MambaAD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月11日(星期六) 下午2:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lewandofskee/MambaAD] About MambaAD-main/model/mambaad.py (Issue #6)





 
Thank you for your interest in our work. Our algorithm is based on the ADer framework, so please put all the files into the ADer framework to run it. The two lines you mentioned are also shown in ADer/model.

**Comment by lewandofskee** [comment]
[resnet34](https://drive.google.com/file/d/1LwKSc7YbRSLzNDJvqUIy9rwbOfTx-1TZ/view?usp=drive_link), [wideresnet50](https://drive.google.com/file/d/10z9lktaZj3By1S4dHFm5BMFhqXZ-Ii1h/view?usp=drive_link).
