### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by duoqingxiaowangzi** [lewandofskee/MambaAD#8]
![image](https://github.com/lewandofskee/MambaAD/assets/117001352/ba269a37-fd62-4572-9ba7-8da1fc86f92f)
作者你好，我按照你的说法将mamba的repo下载并放到ader的文件夹下面了，那运行ader的run.py时run.py中的from configs import get_cfg和from trainer import get_trainer是不是应该用mamba里面configs和trainer文件夹里的代码块

**Comment by lewandofskee** [comment]
Yes! that's right.
