### ISSUE TITLE
How to reproduce mambaad on ader

### ISSUE THREAD

**Issue by jcjlin** [lewandofskee/MambaAD#9]
![image](https://github.com/user-attachments/assets/a6e0bcd7-f960-45c3-a4b6-c4ca01d72636)

Hi! Thank you for providing this amazing project! 
I have successfully cloned the repository and set up the necessary dependencies and dataset (MVTec). 
However, I am a bit unsure about how to proceed with reproducing the results. Could you kindly provide more detailed steps for running the model after the setup?

**Comment by lewandofskee** [comment]
First, you need to copy the contents of the mambaad repository to ader, MambaAD and ADer should be the same level of directory, for example, after copying the directory should be
**ader/configs/mambaad**

Next, You can then run the following command to start the training:

**CUDA_VISIBLE_DEVICES=0 python3 run.py -c configs/mambaad/mambaad_mvtec.py -m train**
